In [6]:
def add(a, b) :
    return a+b

In [7]:
add('a',2)

TypeError: can only concatenate str (not "int") to str

In [9]:
from functools import wraps
from time import perf_counter
from datetime import datetime, timezone

In [14]:
start = perf_counter()

In [15]:
end = perf_counter()

In [16]:
end-start

2.6152794000008726

In [17]:
datetime.now()

datetime.datetime(2024, 1, 21, 14, 5, 50, 196925)

In [19]:
start = datetime.now()

In [20]:
end = datetime.now()

In [21]:
end-start

datetime.timedelta(seconds=2, microseconds=567946)

In [27]:
start.weekday()

6

In [67]:
class Tag:
    def __init__(self, tag):
        self._tag = None 
        self.tag = tag
    
    @property
    def tag(self):
        return self._tag
    
    @tag.setter
    def tag(self,tag):
        self._tag = tag
        
    def __enter__(self):
        print(f'<{self._tag}>',end='')
    
    def __exit__(self,exc_type,exc_value,tbl):
        print(f'</{self._tag}>',end='')
        
        

In [82]:
class Tag:
    def __init__(self, tag):
        self._tag = None 
        self.tag = tag
    
    @property
    def tag(self):
        return self._tag
    
    @tag.setter
    def tag(self,tag):
        self._tag = tag
        
    def __enter__(self):
        print(f'<{self._tag}>',end='')
    
    def __exit__(self,a,b,c):
        print(f'</{self._tag}>',end='')
        
        

In [83]:
t1 = Tag('p')

In [84]:
t1.tag

'p'

In [85]:
t1.__enter__()

<p>

In [86]:
with Tag('p'):
    print('hello',end='')

<p>hello</p>

In [87]:
import decimal

In [92]:
class Precision:
    import decimal
    
    def __init__(self,prec):
        self.prec = prec
        self.default_prec = decimal.getcontext().prec
    
    def __enter__(self):
        decimal.getcontext().prec = self.prec
    
    def __exit__(self,a,b,c):
        decimal.getcontext().prec = self.default_prec

In [98]:
a=decimal.Decimal(1)
b = decimal.Decimal(3)
with Precision(8):
    print(a/b)
print(a/b)

0.33333333
0.33


In [1]:
import numpy as np
#np.set_printoptions(precision=8)
print(np.pi * np.arange(8))

[ 0.          3.14159265  6.28318531  9.42477796 12.56637061 15.70796327
 18.84955592 21.99114858]


In [109]:
np.get_printoptions()['precision']

8

In [36]:
class Precision:
    import numpy as np
    
    def __init__(self,prec):
        self.prec = prec
        self.default_prec = np.get_printoptions()['precision']
    
    def __enter__(self):
        np.set_printoptions(precision=self.prec)
    
    def __exit__(self,a,b,c):
        np.set_printoptions(precision=self.default_prec) 

In [40]:
print(np.pi * np.arange(4))
print('-----------------')
##########
with Precision(2):
    print(np.pi * np.arange(4))
##############
print('-----------------')
print(np.pi * np.arange(4))

[0.         3.14159265 6.28318531 9.42477796]
-----------------
[0.   3.14 6.28 9.42]
-----------------
[0.         3.14159265 6.28318531 9.42477796]


In [124]:
def dv(a, b) :
    try:
        return a/b
    except ZeroDivisionError:
        return ZeroDivisionError.message
    

In [125]:
print("Examples")
assert dv(4,2)==2

Examples


In [11]:
class Percision:
    import numpy as np
    
    def __init__(self,precision):
        self._precision = None
        self.precision = precision
    
    @property
    def precision(self):
        return self._precision
    
    @precision.setter
    def precision(self,precision):
        self._precision = precision
        
    def __enter__(self):
        
    

In [12]:
pr1 = Percision(5)

In [13]:
print(pr1.precision)

5


In [32]:
class Tag:
    
    def __init__(self,tag):
        self.tag = tag
    
    def __enter__(self):
        print(f'<{self.tag}>',end='')
        
    def __exit__(self,a,b,c):
        print(f'</{self.tag}>',end='')
    
    

In [34]:
with Tag('P'):
    print('hello',end='')

<P>hello</P>

In [20]:
with Tag

5

In [21]:
sm1.a=51
sm1.a

51