In [60]:
class Precision:
    import numpy as np
    
    def __init__(self,prec):
        self.prec = prec
        self.default_prec = np.get_printoptions()['precision']
    
    def __enter__(self):
        np.set_printoptions(precision=self.prec)
    
    def __exit__(self, exc_type, exc_value, exc_tb):
        np.set_printoptions(precision=self.default_prec) 

In [61]:
import numpy as np
print(np.array([np.pi]))
print('-----------------')
##########
with Precision(2):
    print(np.array([np.pi]))
##############
print('-----------------')
print(np.array([np.pi]))

[3.14159265]
-----------------
[3.14]
-----------------
[3.14159265]


In [17]:
import numpy as np
print(np.pi * np.arange(1,4))
print('-----------------')
##########
with Precision(2):
    print(np.pi * np.arange(1,4))
##############
print('-----------------')
print(np.pi * np.arange(1,4))

[3.14159265 6.28318531 9.42477796]
-----------------
[3.14 6.28 9.42]
-----------------
[3.14159265 6.28318531 9.42477796]


In [28]:
import numpy as np
print(np.array([np.pi]))
print('-----------------')
##########
with Precision(2):
    print(np.array([np.pi]))
##############
print('-----------------')
print(np.array([np.pi]))

[3.14159265]
-----------------
[3.14]
-----------------
[3.14159265]


In [20]:
p1 = np.pi * np.arange(1,4)
type(p1)

numpy.ndarray

In [27]:
p1 = np.array(3.141592653589793)
import numpy as np
print(p1)
print('-----------------')
##########
with Precision(2):
    print(p1)
##############
print('-----------------')
print(p1)

3.141592653589793
-----------------
3.141592653589793
-----------------
3.141592653589793


In [29]:
class Tag:    
    def __init__(self,tag):
        self.tag = tag
    
    def __enter__(self):
        print(f'<{self.tag}>',end='')
        
    def __exit__(self,a,b,c):
        print(f'</{self.tag}>',end='')

In [30]:
with Tag('P'):
    print('hello',end='')

<P>hello</P>

In [41]:
with Tag('P') as tg1:
    tg1.tag='A'
    print('hello',end='')

<P></P>

AttributeError: 'NoneType' object has no attribute 'tag'

In [58]:
class Tag:    
    def __init__(self,tag):
        self.tag = tag
    
    def __enter__(self):
        print(f'<{self.tag}>',end='')
        
    def __exit__(self,a,b,c):
        print(f'</{self.tag}>',end='')

In [59]:
with Tag('p'):
    print('inside p tag',end='')

<p>inside p tag</p>